language: python

cache: pip

python:
- "3.8"

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: syntax
      install: pip install black flake8
      script:
        - black --check .
        - flake8 .
    - name: packaging
      install: pip install .[release]
      script: setl publish --no-upload
    - stage: primary
      install: pip install .[test]
      script: pytest tests/test_basic.py
    - stage: secondary
      python: "3.7"
    - python: "3.6"
    - python: "nightly"
  allow_failures:
    - python: "nightly"

install: pip install .[test]

script: pytest tests
