language: python

cache: pip

jobs:
  fast_finish: true
  include:
    - name: packaging
      install: pip install .[release]
      script: setl publish --no-upload
    - stage: primary
      python: "3.8"
    - python: "2.7"
    - stage: secondary
      python: "3.7"
    - python: "3.6"
    - python: "nightly"
  allow_failures:
    - python: "nightly"


install: pip install .[test]

script: pytest tests
