language: python

cache: pip

python:
- "3.8"
- "3.7"
- "3.6"

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: syntax
      install: pip install black flake8
      script:
        - black --check .
        - flake8 .
    - name: packaging
      install: pip install .[release]
      script: setl publish --no-upload
    - stage: simple
      install: pip install .[test]
      script: pytest tests/test_simple.py
    - stage: complex
      install: pip install .[test]
      script: pytest tests/test_complex.py

